export const DELIVERY_STATUS = {
    PENDING: 'PENDING',
    ASSIGNED: 'ASSIGNED',
    SHIPPED: 'SHIPPED',
    PARTIAL_DELIVERY: 'PARTIALDELIVERY',
    DELIVERED: 'DELIVERED',
    CANCELLED: 'CANCELLED'
}